# -*- coding: utf-8 -*-
"""Journal Data.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/14x-cpVsg3NDGdiLkHkihWCwubY_oknTI
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from google.colab import files

uploaded = files.upload()

import io
df = pd.read_excel(io.BytesIO(uploaded['Impact-Factor-Ratings.xlsx']))
df.head(5)

df.describe

count_null = df.isnull().values.sum()
print(count_null)

df.dropna()

new = df['Highest percentile'].str.split('\n',n=2,expand=True)
new

new1 = new[1].str.split('/',n=1,expand=True)
new1

df['HP_percentile'] = new1[0]
df['HP_Frequency'] = new[1]
df['HP_subject'] = new[2]
df.head()

df.drop('Highest percentile',axis=1,inplace=True)
df.head()

#data visualization

source_title = df['Source title']
citescore = df['CiteScore']
citations = df['2016-19 Citations']
documents =df['2016-19 Documents']
citedpercent = df['% Cited']
SNIP = df['SNIP']
SJR = df['SJR']
publisher = ['Publisher']
HP_percentile = ['HP_percentile'] 
HP_frequency = ['HP_frequency']
HP_subject = ['HP_subject']

plt.plot(source_title,citescore)
plt.xlabel('Source Title')
plt.ylabel('Cite score')
plt.show()

fig1,size1 = plt.subplots()
size1.pie(citescore,shadow=True,startangle=0)